### ISSUE TITLE
installing pyfiglet on a specific python version

### ISSUE THREAD

**Issue by radogit** [mechmotum/whosnext#6]
Not so much an issue, but perhaps an addition to the readme, as this was an issue I just helped resolve and getting whosnext running. 
Many of us run multiple python versions on a single machine (worse yet multiple python3 installs, both in bin and elsewhere for anaconda) and running 'pip install pyfiglet' does not make it available to all installations. 
Admittedly this is a python/pip/machine -specific issue, but an immediate obstacle nonetheless.
This worked just now to alleviate said issue.

```
which python
whereis python
ls -ls /usr/bin/python*
python3.9 -m pip install pyfiglet
python3.9 whosnext.py

```

**Comment by moorepants** [comment]
Yes, the official recommendation is to use `python -m pip install ...` so that pip is called from the python you are using.

https://pip.pypa.io/en/stable/getting-started/

Feel free to explain as much as you want about this in the readme.

**Comment by moorepants** [comment]
Installation instructions are present.
