### ISSUE TITLE
feature proposal: clemency if one has presented within the last X sessions

### ISSUE THREAD

**Issue by radogit** [mechmotum/whosnext#7]
Looking at the past presentation list, it has occurred recently that a person has rolled despite having recently presented. As is, to my understanding, the script will let the roll randomly decide, resulting in albeit low but regardless, a likelihood of presenting multiple times vs. another person not rolling once. The current weighting lowers the likelihood but does not eliminate it.

Introducing this clemency, assuming 20 yearly sessions, 10 lab members, and an 'clemency' of 6 months/10 sessions, would have the script as good as ensure that everyone goes exactly twice a year. Admittedly this would lead to a moving 6 month window and a resulting strict repetitive schedule, where the die from that moment on has only a single lab member to choose from, the one who presented 6month+1 day ago. Setting the clemency at 3 months could be a good middle ground.

**Comment by moorepants** [comment]
I browsed the code and you can be chosen two sessions in a row, theoretically. We can add a 4 session (two month) period you can't be chosen easy enough.

**Comment by moorepants** [comment]
I was wrong about that. We had a 15 day (2 session) grace period.
